### ISSUE TITLE
How to use with mbox

### ISSUE THREAD

**Issue by dnaura** [rendezz/Zinkuba#1]
Hello,
Nice program : I use it with Imap with no problem.
But with mbox , I don't understand well how to use the interface.
I am using mails exported from Thunderbird to mbox  via ImportExportTools extension.
Can you help me please?
Thanks.
Best regards.
David.

**Comment by rendezz** [comment]
I am not sure what you are having issues with and I haven’t used the mbox function in a while (and used it on a mac export)  But with Mbox, each mbox is a folder.  As opposed to imap, where there is account with sub folders.

Can you elaborate on your issue?  Or send me some screenshots/test cases, so I can take a look

Thanks

Darren

On Jul 13, 2016, at 3:18 PM, dnaura <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello,
Nice program : I use it with Imap with no problem.
But with mbox , I don't understand well how to use the interface.
I am using mails exported from Thunderbird to mbox via ImportExportTools extension.
Can you help me please?
Thanks.
Best regards.
David.

**Comment by luposung** [comment]
Hi, 
There's no output .pst file after the number next to 'No Progress Info' stop counting. The .mbox was exported from Mac Mail.app. OS is windows 10.
Thanks for any feedback.

Cheers!
PS
![zinkuba](https://cloud.githubusercontent.com/assets/472011/22277951/a27386de-e2fa-11e6-9bd1-25a037194aad.PNG)

**Comment by razor911bv** [comment]
Any updates on this? :)

**Comment by rendezz** [comment]
I haven't had a chance to look at this yet, I will be doing some dev on zinkuba this week and I will try look at this.

**Comment by rendezz** [comment]
Hi,

So I have tested the mbox exporter and it works fine
Mbox works slightly differently in that you need an Mbox file for every folder.
So when you load an mbox file it takes that file (or the folder it was in) as the destination folder name.
If you load Hello/mbox, it will automatically choose Hello as the folder to import into.  You can change this by editing the Folder Name Field.
The Account Name Field is the name of the account (which in other worlds would be jeff@microsoft.com or something.  But you can name it anything.  This is also the name of the PST that ends up (e.g. Zinkuba-jeff@microsoft.com.pst)

In the screenshotted example above, I see a big count problem, 835 failures.  This might  be because the pst was unable to be generated or the folder name was not compatible.  To find this you can look at the log file zinkuba.log which is generated in the same windows folder as the zinkuba exe

Or send that to me and I will take a look at the log for you.

The reason why there is no progress info, is because for the other sources, we can get message counts up front.  But mbox doesn't work like that, its all the mails mushed together in a single file, I would have to parse the entire file, just to get the message count.  So thats just life for mbox files.

I think I see a small bug in the count of processed messages, which I will fix now and release with my other updates.

**Comment by d1ddle** [comment]
Hi, I'm trying to process an mbox file named Mail/Inbox.mbox and am getting these errors in the log:

```
System.Exception: MrMapi failed to process file C:\Users\hayde\AppData\Local\Temp\tmp62CE.tmp with exit code 0
Message File Converter
Options specified:
   Input File: C:\Users\hayde\AppData\Local\Temp\tmp62CE.tmp
   Output File: C:\Users\hayde\AppData\Local\Temp\5bac6817-c187-47b3-b9d3-ae7dc0675381.msg
   Conversion Type: MIME -> MAPI
MAPI <-> MIME converter not found. Perhaps Outlook is not installed.

   at Zinkuba.MailModule.MessageProcessor.RawToMsgProcessor.ConvertRawToMsg(RawMessageDescriptor message)
   at Zinkuba.MailModule.MessageProcessor.RawToMsgProcessor.ProcessMessage(RawMessageDescriptor message, MessageProcessState state)
2022-06-11 02:30:53 [d1ddle-producer] ERROR .MessageProcessor.RawToMsgProcessor.ProcessMessage – Failed to process raw [20] into msg : MrMapi failed to process file C:\Users\hayde\AppData\Local\Temp\tmp65BD.tmp with exit code 0
Message File Converter
Options specified:
   Input File: C:\Users\hayde\AppData\Local\Temp\tmp65BD.tmp
   Output File: C:\Users\hayde\AppData\Local\Temp\af3b26f4-3f18-4ace-b2fa-4dc89aacf7e0.msg
   Conversion Type: MIME -> MAPI
MAPI <-> MIME converter not found. Perhaps Outlook is not installed.
```

Any suggestions?
EDIT: I have Outlook installed, have run the Click2fix.bat as admin multiple times, am running Zinkuba as admin and can see outlook running in the tray during the conversion but don't have any windows open.
Windows 11 x64

**Comment by rendezz** [comment]
Hi

Do you have outlook installed on the machine?  To write to PST’s you need outlook and if its a recent version, you need to apply the reg patch which is included in the repo.

Thanks

On 11 Jun 2022, at 15:39, d1ddle ***@***.******@***.***>> wrote:



Hi, I'm trying to process an mbox file named Mail/Inbox.mbox and am getting these errors in the log:

System.Exception: MrMapi failed to process file C:\Users\hayde\AppData\Local\Temp\tmp62CE.tmp with exit code 0
Message File Converter
Options specified:
Input File: C:\Users\hayde\AppData\Local\Temp\tmp62CE.tmp
Output File: C:\Users\hayde\AppData\Local\Temp\5bac6817-c187-47b3-b9d3-ae7dc0675381.msg
Conversion Type: MIME -> MAPI
MAPI <-> MIME converter not found. Perhaps Outlook is not installed.

at Zinkuba.MailModule.MessageProcessor.RawToMsgProcessor.ConvertRawToMsg(RawMessageDescriptor message)
at Zinkuba.MailModule.MessageProcessor.RawToMsgProcessor.ProcessMessage(RawMessageDescriptor message, MessageProcessState state)
2022-06-11 02:30:53 [d1ddle-producer] ERROR .MessageProcessor.RawToMsgProcessor.ProcessMessage – Failed to process raw [20] into msg : MrMapi failed to process file C:\Users\hayde\AppData\Local\Temp\tmp65BD.tmp with exit code 0
Message File Converter
Options specified:
Input File: C:\Users\hayde\AppData\Local\Temp\tmp65BD.tmp
Output File: C:\Users\hayde\AppData\Local\Temp\af3b26f4-3f18-4ace-b2fa-4dc89aacf7e0.msg
Conversion Type: MIME -> MAPI
MAPI <-> MIME converter not found. Perhaps Outlook is not installed.

Any suggestions?

**Comment by Nikki-Devil** [comment]
Hi, I have the same problem
I have Office 2021 (and so Outlook) installed
Running the patch and running it in admin did something since before it wouldn't even create a pst
I also ran the program as admin after using the patch but it didn't change the result

It doesn't write anything in the pst, it seems to have 256Kb wich is a classic empty pst file while my mbox should have around 250Mb of data (confirmed blank after opening it in Outlook)

I have the same error in the log than the person who commented before :
(The log file ends by : 
"                   Conversion Type: MIME -> MAPI
MAPI <-> MIME converter not found. Perhaps Outlook is not installed.")

Edit : I'm on Windows 10, the Outlook tray icon shows up after using the program (even while I didn't launched it)
x86-64 architecture so it won't be a weird windows architecture compatibility issue
Edit2 : I tested on a Win11 VM with Office 365 downloaded from Microsoft itself and it did the exact same result (Launched Outlook, quit and launched the patch, launched the program, a new blank pst is created and the log inform about the same error without inflating the pst)
